<#----------------------------------
    .SYNOPSIS  
        Create multiple dummy log files.
    .NOTES 
	   Created to test some .zip functionality. Creates multiple files and hopefully differnet directories
    .AUTHOR
        Author
    .LOGIC
        For loop created to create files with name format of "File_00 {incrementing number}".log. Creates as many as you need, using the textvalue field. The usual file size is 12KB.
    .FUNCTIONS
	   Functions written into code
    .VERSION
        1.0
    .EXAMPLE USAGE
	   Run this from either ISE, VS Code, or just as a regular .ps1 file
----------------------------------#>

$textvalue = "Lorem Ipsum
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In in blandit justo. Vivamus tincidunt auctor fermentum. Nunc a rhoncus nisl. Mauris faucibus urna non dolor ullamcorper, sed ultrices felis ultrices. Suspendisse ac eros ut lectus finibus cursus vel eu lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mollis ullamcorper neque, vitae pretium neque tincidunt ac. Integer dolor sem, finibus eu pulvinar vitae, feugiat consectetur libero. Morbi posuere elit mi, in tempor massa varius sed. Donec placerat ipsum eu vulputate pellentesque. Vivamus fermentum euismod metus sed commodo. Nulla finibus metus non diam imperdiet, nec bibendum urna luctus.
Donec efficitur bibendum dictum. Nulla volutpat diam sit amet elit fermentum vulputate. Aliquam mollis sodales magna. Donec in egestas nisi. Nunc eu ornare orci. Aliquam ultricies porttitor augue in dapibus. Maecenas fermentum metus ut metus ornare convallis. Integer tincidunt sem ac tellus imperdiet, at gravida ligula efficitur. Pellentesque vitae feugiat risus, a ullamcorper libero.
Integer tempus ex eros, ut auctor dui gravida a. Nam lacinia erat eget turpis scelerisque malesuada. Duis a porta tortor. Praesent faucibus odio id finibus vehicula. Quisque mauris purus, rhoncus dictum libero ac, molestie consectetur lectus. Integer et tristique quam, id rhoncus augue. Curabitur sollicitudin tellus nec nisl ultricies vestibulum. Maecenas ac varius lacus.
Pellentesque porta est turpis, quis tincidunt dolor pharetra quis. Vivamus consectetur leo a ultricies porttitor. Praesent ultricies elit nec diam ultricies iaculis. Cras vel nisl velit. Morbi pellentesque tortor et libero finibus blandit. Etiam sodales ante tortor, sit amet convallis ligula suscipit a. Integer eu ligula quis tellus interdum suscipit non ut augue. Praesent ac nisl dui. Curabitur euismod quam ac nisi euismod varius. Praesent tempor odio ante, ut luctus ex fringilla eu. Cras vel varius sem, vel fringilla nibh. Curabitur cursus vehicula diam sed vehicula. Mauris quis imperdiet metus.
Suspendisse auctor accumsan arcu vitae dictum. Morbi tempor ultrices quam maximus sodales. Ut consequat id odio sed vulputate. Phasellus eleifend interdum nibh, non fringilla nisi sodales ut. Aliquam sed tempor mauris, et pellentesque quam. Curabitur ut purus non risus gravida tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ante nibh, auctor eu tempor vitae, aliquam et lorem. Ut id mauris et libero pulvinar interdum. Mauris rhoncus dolor metus, quis luctus ante commodo ac. Morbi id laoreet massa.
Pellentesque et eros hendrerit, fermentum odio eleifend, maximus enim. Vivamus id volutpat tellus, id luctus massa. Nunc pulvinar interdum nisi non bibendum. Duis condimentum sapien vel justo mollis convallis. Donec sed lorem commodo dolor laoreet egestas a quis nibh. Sed faucibus, lectus vitae scelerisque pretium, enim mi pharetra lorem, ac ornare lacus est in tellus. Donec quis efficitur sapien. Integer iaculis convallis tortor, ac commodo massa. Nullam lacinia dapibus ipsum et facilisis.
Duis at ipsum nec dolor dignissim dapibus vel in nibh. Curabitur non viverra est. Integer magna arcu, facilisis quis scelerisque sit amet, egestas nec mi. Aenean non lectus elit. Sed metus nisl, pulvinar sit amet bibendum euismod, porta ultrices mauris. In scelerisque mauris vel risus scelerisque, vitae condimentum tellus ullamcorper. Sed facilisis ac massa et maximus. Nulla nec convallis odio. Mauris lacinia posuere nisi, sed cursus tellus aliquet et. Aliquam accumsan dui sed eleifend egestas. Mauris consequat interdum quam ac consectetur.
Suspendisse sit amet porttitor neque, at sollicitudin mauris. Donec tincidunt leo non diam fermentum finibus. Cras ultrices risus quis felis interdum, a ultricies ipsum interdum. Fusce eget blandit purus. Fusce aliquam mi in urna iaculis, ac mollis libero consequat. Proin purus magna, tempus viverra leo eu, molestie consequat augue. Nam suscipit bibendum maximus.
Morbi semper lacus tortor, in tincidunt enim iaculis ac. Proin tincidunt nunc ac velit posuere, quis fringilla lorem pellentesque. Proin lobortis turpis sit amet lacus interdum semper. Aliquam luctus auctor nisl et congue. Quisque imperdiet porta diam sed dignissim. Suspendisse risus sem, sodales sed vehicula a, tempus sed lectus. Phasellus urna metus, varius finibus blandit sit amet, feugiat condimentum ipsum. Praesent egestas maximus metus non laoreet. Morbi molestie nunc quam, viverra imperdiet lectus luctus in.
Sed porta orci non sem mattis pulvinar. Cras finibus viverra ex, ac feugiat nisl. Aenean dolor velit, luctus sed facilisis ac, pretium et arcu. Curabitur porta quis elit vel ullamcorper. Morbi eu eros at neque pulvinar hendrerit. Mauris ut vehicula dolor, id luctus arcu. Sed eleifend urna a libero cursus mattis. Ut rutrum est consectetur varius condimentum.
Sed erat ipsum, rutrum ut egestas ut, placerat vitae nisi. Curabitur a erat aliquam, tincidunt risus eget, condimentum neque. Vivamus gravida mauris lobortis nisi faucibus, vitae pulvinar lorem elementum. Praesent orci felis, facilisis non tincidunt ac, blandit sit amet lorem. Praesent ut magna ante. Fusce interdum et risus eu gravida. Aenean sit amet varius risus, sit amet pretium lectus. Nam ut ullamcorper leo. Quisque congue purus non tellus rutrum, id sodales nibh blandit.
Nam laoreet, turpis vel tempor lobortis, massa nisi faucibus nisi, et vehicula quam nisi vel risus. Suspendisse pretium mollis erat. In efficitur ullamcorper viverra. Pellentesque lacinia sodales sodales. Donec nisl diam, consequat id erat non, mollis bibendum turpis. Etiam tincidunt arcu quis velit blandit, aliquet facilisis felis semper. Aenean et efficitur erat. Curabitur non feugiat turpis. Nullam at metus eget justo volutpat porttitor vel gravida tellus. Nullam id lectus in ipsum tincidunt commodo. Suspendisse commodo leo turpis, eu maximus dui ullamcorper quis.
Duis dui velit, volutpat ac consectetur ac, scelerisque eget lacus. Nullam eget eros eget nibh finibus rutrum ac at lectus. Quisque vel ipsum sagittis, interdum dui et, efficitur justo. Pellentesque euismod neque quis leo ullamcorper, quis laoreet nibh blandit. Duis varius, ligula eget scelerisque eleifend, arcu dolor tincidunt lacus, ut tristique sem eros vel dui. Sed tellus ex, egestas ac feugiat ac, fermentum eu dolor. Aenean ullamcorper lectus ac eleifend bibendum. Nunc lacinia metus a porttitor iaculis. Proin consectetur bibendum dui, ac pharetra tortor vestibulum eu. Vestibulum quis laoreet lectus. Integer aliquet mi sit amet tellus fermentum, tincidunt fermentum magna facilisis.
Nunc sit amet venenatis urna. Donec a quam eget risus tempus molestie ac sit amet ante. In lacinia massa magna, ac mattis purus faucibus id. Proin aliquam quam faucibus quam tincidunt, non fermentum leo ornare. Maecenas fermentum felis ex, nec suscipit eros hendrerit quis. Vivamus suscipit diam quam, vitae blandit turpis convallis a. Quisque non sapien eu felis porttitor rutrum quis nec arcu. Suspendisse eget volutpat lectus. Phasellus ullamcorper tellus eu magna posuere pretium. Integer vehicula nibh sed eros pharetra bibendum. Pellentesque quis tristique urna, ac ornare orci. Quisque gravida non diam et dictum. Donec porttitor ligula lacus, non tempus justo bibendum in. Praesent non porta lacus. Maecenas iaculis blandit lacus, nec fermentum magna tempor nec. Cras dignissim lacus non erat gravida malesuada.
Aenean commodo at magna id vehicula. Duis turpis neque, cursus non gravida nec, ullamcorper quis eros. Duis id mauris est. Phasellus gravida, quam in sollicitudin molestie, lacus enim pretium massa, vel congue dolor risus et quam. Maecenas euismod velit quis nisi pretium, bibendum blandit lacus fringilla. Morbi consequat tincidunt malesuada. Integer interdum mollis elit non interdum. Nullam et lectus eget metus ornare sollicitudin in ac augue. Vivamus vitae nulla facilisis, tincidunt nibh id, ullamcorper elit. Sed condimentum sollicitudin mauris, sit amet blandit est bibendum at. Proin et commodo metus. Etiam ullamcorper quam a purus pretium, sit amet blandit risus feugiat. Vestibulum facilisis est id molestie vehicula. Nullam ac congue metus. Quisque ac elit massa. Donec ac mauris quis ante eleifend venenatis.
Sed non enim ac elit ullamcorper aliquam molestie sit amet enim. Sed arcu elit, viverra sed mauris at, sagittis elementum risus. Sed non orci neque. Duis iaculis id enim consectetur convallis. Nullam fermentum, tellus vitae interdum scelerisque, massa tellus cursus augue, ut gravida lorem eros id nibh. Aenean eu hendrerit nunc. Donec vel auctor elit. Phasellus dictum feugiat vestibulum. Maecenas congue augue nec nisi finibus facilisis. Nulla vel diam id felis auctor posuere. Suspendisse potenti. Donec egestas mollis lobortis. Fusce molestie, ex vel feugiat commodo, lectus dolor condimentum nisl, quis pellentesque nulla sapien sit amet dolor. Fusce ornare eget est nec aliquam.
Ut ultrices, mauris id tincidunt ornare, arcu massa iaculis nisl, eu sagittis quam lectus in nibh. Curabitur molestie diam eget pulvinar sodales. Phasellus pretium, lorem et pulvinar commodo, nisl felis tempor dolor, sed hendrerit velit purus in massa. Proin efficitur aliquam orci at dignissim. Morbi cursus nisl a ex commodo, in vestibulum augue egestas. Donec varius mi mi, vel tristique orci condimentum ut. Donec non viverra lorem. Nulla dictum ut enim sit amet luctus. Ut vitae neque auctor, tristique eros et, eleifend sapien. Ut porta, nibh sit amet viverra facilisis, orci risus egestas metus, quis ullamcorper nisl ligula id orci. Nunc sit amet tempor urna. Integer ut laoreet mi, vel imperdiet dolor.
In posuere sagittis semper. Aenean consectetur, lectus vel dignissim semper, massa massa blandit ligula, ut elementum lectus libero sit amet turpis. Sed malesuada erat velit, et pellentesque nulla vehicula non. Donec neque eros, placerat in nibh vitae, bibendum consectetur ligula. Etiam libero ante, ultrices in purus dapibus, ornare volutpat diam. Vestibulum sed nulla non quam pulvinar finibus in et urna. Praesent neque leo, euismod quis rutrum eu, volutpat eget sapien.
Praesent imperdiet neque orci, et dictum leo tempus id. Integer aliquet suscipit ex. In efficitur odio non pellentesque dapibus. Ut rutrum lorem vel eros condimentum, id vulputate enim gravida. Donec facilisis, sapien vel finibus tristique, ex neque egestas mi, non interdum libero metus ullamcorper nisi. Mauris tristique, felis vel faucibus pharetra, nulla sem porta nulla, pharetra sagittis magna odio at neque. Ut venenatis ullamcorper turpis, eu vulputate purus. Praesent mollis feugiat tincidunt. Quisque vehicula magna ut nulla tempus sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas in ultricies magna.
Aliquam placerat libero ut velit sodales, eget aliquam odio porttitor. Fusce id leo eu lectus posuere faucibus. Morbi ullamcorper facilisis dui quis dapibus. Nulla volutpat feugiat nisl in molestie. Donec odio velit, tincidunt rutrum ligula et, imperdiet commodo velit. Maecenas tellus mi, luctus ac gravida quis, aliquam id metus. Sed fringilla egestas felis, vitae tristique velit eleifend blandit. Donec libero nulla, mattis sed justo id, consequat maximus massa. Fusce ut nisl placerat, blandit velit ac, pharetra dolor. Donec condimentum eget urna vel molestie. In ante mi, pellentesque id finibus vel, scelerisque ut nulla. Donec nec dapibus lorem, id sodales elit. Pellentesque dapibus quam ac erat hendrerit, et maximus ligula tempus. Integer nec elit ligula. Fusce euismod venenatis purus. Ut venenatis volutpat turpis, eu bibendum ante faucibus vel."


$filepath = "D:\_temp\" # pre-programatically
#$filepath = read-host "Enter the directory" # Get filepath from user input. Doesn't create the folder though. You have to create it first with the "\" character at the end.

$filename = "File_00" # file name
$fileext = ".log" # file extension
$filenum = read-host "How many files do you want to create?" # prompt user for number of files to create
$i = $null #resets the counter for number of files

for ($i=0;$i-le $filenum;$i++){
    Set-content -Path $filepath$filename$i$fileext -Value $textvalue
}
Write-host $i files created in $filepath

